@baseUrl = http://localhost:3000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWxpQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjQwMjkyMDEsImV4cCI6MTc2NDAzMDEwMX0.EuC8xfZyKzH3N10QnWTt7vhtJZLtCtzNt52poW8oy4k
### 1) Registrar usuario
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "nombre": "Tobias",
  "email": "tobias@example.com",
  "password": "1234567"
}

###

### 2) Login usuario
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "juli@example.com",
  "password": "123456"
}

# Después de correr esto, copiar el accessToken de la respuesta
# y pegarlo arriba en @token = ...

###

### 3) Obtener todas las recetas (protegido con JWT)
GET {{baseUrl}}/api/recetas
Authorization: Bearer {{token}}

###

### 4) Crear una receta nueva
POST {{baseUrl}}/api/recetas
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Tarta de atun",
  "ingredientes": "Harina, huevo, atun, cebolla",
  "instrucciones": "Saltear cebolla, mezclar todo, hornear 30 minutos."
}

###

### 5) Obtener una receta por ID
GET {{baseUrl}}/api/recetas/7
Authorization: Bearer {{token}}

###

### 6) Actualizar una receta
PUT {{baseUrl}}/api/recetas/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Tarta de atun (actualizada)",
  "ingredientes": "Harina, huevo, atun, cebolla, queso",
  "instrucciones": "Mezclar, agregar queso y hornear 35 minutos."
}

###

### 7) Borrar una receta
DELETE {{baseUrl}}/api/recetas/4
Authorization: Bearer {{token}}

###

### 8) Exportar recetas a CSV
GET {{baseUrl}}/api/recetas/exportar
Authorization: Bearer {{token}}

###

### 9) Borrar TODAS las recetas (solo si NODE_ENV === "test")
DELETE {{baseUrl}}/api/recetas/all
Authorization: Bearer {{token}}

### 10) Ver estadísticas de recetas
GET {{baseUrl}}/api/recetas/estadisticas
Authorization: Bearer {{token}}
